# Generated by Django 5.2.12 on 2026-05-01 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0003_alter_category_options_alter_snack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'verbose_name': 'Chi tiết giỏ hàng', 'verbose_name_plural': 'Chi tiết giỏ hàng'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Giỏ hàng'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.snack', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá'),
        ),
    ]
