# Generated by Django 5.2.12 on 2026-05-01 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_alter_category_options_alter_snack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(default='COD', max_length=50, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiverName',
            field=models.CharField(max_length=255, verbose_name='Tên người nhận'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('shipped', 'Đang giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.snack', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá'),
        ),
    ]
