# Generated by Django 5.2.12 on 2026-05-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
