# Generated by Django 5.2.12 on 2026-05-01 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_snack_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='snack',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả danh mục'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='products.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Hình ảnh (URL)'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='snackName',
            field=models.CharField(max_length=255, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái (Còn bán)'),
        ),
    ]
