# Generated by Django 5.2.12 on 2026-05-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_snack_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='soldCount',
            field=models.IntegerField(default=0, verbose_name='Đã bán'),
        ),
    ]
